project: decision_for_screening

# -- Initiation characteristics of the model
model_type: "linear"
value_function: "rel_pcmi"
elicit: False
patient_chars: {"Age": "age_4_adult", 
                        "Sex": "M",
                        "SD": "SD_2_normal",
                        "PA": "PA_2",
                        "Smoking": "sm_1_not_smoker",
                        "BMI": "bmi_2_normal",
                        "Alcohol": "low",
                        #"Diabetes": True,
                        #"Hypertension": True,
                        }

# -- Flag for assigning a new test
new_test: False 

# --------- If new_test = True, the following parameters must be defined
cost_new_test: 3
sensitivity_new_test: 0.85
specificity_new_test: 0.94



# -- For the elicitation step
PE_cost: 300          # Probability equivalent cost
PE_info: 0.4          # Probability equivalent info
PE_prob: 0.7          # Probability of equivalence


# -- Lower bound of estimation of performance metrics

sens_analysis_metrics_lower: 
  screening: [
    # Specificity
    1, 0, 0,          # No screening
    0, 0.843, 0.157,  # gFOBT
    0, 0.92, 0.08,    # FIT
    0, 0.606, 0.394,  # Blood-based
    0, 0.859, 0.141,  # Stool DNA
    0, 0.89, 0.11,    # CTC
    0, 0.89, 0.11,    # Colon capsule

    # Sensitivity
    1, 0, 0,          # No screening
    0, 0.631, 0.369,  # gFOBT
    0, 0.35, 0.65,    # FIT
    0, 0.212, 0.788,  # Blood-based
    0, 0.170, 0.830,  # Stool DNA
    0, 0.05, 0.95,    # CTC
    0, 0.17, 0.83,    # Colon capsule
  ]

  colonoscopy: [
  
    # Specificity
    1, 0, 0,          # No colonoscopy
    0, 0.99, 0.01,    # Colonoscopy

    # Sensitivity
    1, 0, 0,          # No colonoscopy
    0, 0.03, 0.97,    # Colonoscopy
  ]



sens_analysis_metrics_upper: {
  "screening": [

    # Specificity
    1, 0, 0,          # No screening
    0, 0.961, 0.039,  # gFOBT
    0, 0.95, 0.05,    # FIT
    0, 0.786, 0.214,  # Blood-based
    0, 0.872, 0.128,  # Stool DNA
    0, 0.89, 0.11,    # CTC
    0, 0.95, 0.05,    # Colon capsule

    # Sensitivity
    1, 0, 0,          # No screening  
    0, 0.418, 0.582,  # gFOBT
    0, 0.11,  0.89,   # FIT
    0, 0.068, 0.932,  # Blood-based
    0, 0.025, 0.975,  # Stool DNA
    0, 0.05,  0.95,   # CTC
    0, 0.09,  0.91,   # Colon capsule

  ],

  "colonoscopy": [

    # Specificity
    1, 0, 0,          # No colonoscopy
    0, 0.99, 0.01,    # Colonoscopy

    # Sensitivity
    1, 0, 0,          # No colonoscopy
    0, 0.03,  0.97,   # Colonoscopy
  ],

}




# -- Assignning colors to the different screening strategies
colors:
  No_screening: '#1f77b4'
  gFOBT: '#ff7f0e'
  FIT: '#2ca02c'
  Blood_based: '#d62728'
  Stool_DNA: '#9467bd'
  CTC: '#8c564b'
  Colon_capsule: '#e377c2'
  Colonoscopy: '#bcbd22'
  New_test: '#17becf'        # Possible name for new test, change if necessary.
  H(CRC): '#7f7f7f' 
  