project: decision_for_screening

# -- Initiation characteristics of the model
model_type: "linear"
value_function: "rel_pcmi"
elicit: False
patient_chars: {"Age": "age_4_adult", 
                        "Sex": "M",
                        "SD": "SD_2_normal",
                        "PA": "PA_2",
                        "Smoking": "sm_1_not_smoker",
                        "BMI": "bmi_2_normal",
                        "Alcohol": "low",
                        #"Diabetes": True,
                        #"Hypertension": True,
                        }

# -- Flag for assigning a new test
new_test: False 

# --------- If new_test = True, the following parameters must be defined
cost_new_test: 3
sensitivity_new_test: 0.85
specificity_new_test: 0.94



# -- For the elicitation step
PE_cost: 300          # Probability equivalent cost
PE_info: 0.4          # Probability equivalent info
PE_prob: 0.7          # Probability of equivalence


# -- Assignning colors to the different screening strategies
colors:
  No_screening: '#1f77b4'
  gFOBT: '#ff7f0e'
  FIT: '#2ca02c'
  Blood_based: '#d62728'
  Stool_DNA: '#9467bd'
  CTC: '#8c564b'
  Colon_capsule: '#e377c2'
  Colonoscopy: '#bcbd22'
  New_test: '#17becf'        # Possible name for new test, change if necessary.
  H(CRC): '#7f7f7f' 
  